### ISSUE TITLE
Thread-safe processing of subscription information

### ISSUE THREAD

**Issue by muchengyang** [christophersmith/summer-mqtt-samples#1]
Hi christophersmith:
I hope to get your help，Subscribe to the same topic with multiple threads, how to ensure that messages are consumed by only one thread，The code is as follows。

**Comment by christophersmith** [comment]
@ycy1991 No code samples were provided by you. It would help to see what you are doing. Is there a reason that you've creating a client for each thread and subscribing to the same topic?

As far as guaranteed delivery to one, and only one, client that has subscribed make sure that the message is being published with a Quality of Service of 2 (com.github.christophersmith.summer.mqtt.core.MqttQualityOfService.QOS_2). https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/

**Comment by christophersmith** [comment]
Closing due to lack of follow up information.
